/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#1b1b1c',
        'surface-tint': '#b52619',
        'tertiary-fixed-dim': '#c1c7cf',
        'on-tertiary-container': '#a9b0b7',
        'secondary-fixed-dim': '#c8c6c7',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        surface: '#f8f9ff',
        tertiary: '#272d33',
        'inverse-surface': '#213145',
        'primary-fixed': '#ffdad4',
        'primary-fixed-dim': '#ffb4a8',
        'on-primary-fixed-variant': '#920703',
        'error-container': '#ffdad6',
        'surface-container': '#e5eeff',
        'surface-dim': '#cbdbf5',
        'on-background': '#0b1c30',
        'on-secondary-fixed-variant': '#474647',
        'surface-container-high': '#dce9ff',
        'on-surface': '#0b1c30',
        secondary: '#5f5e5f',
        'surface-container-highest': '#d3e4fe',
        'outline-variant': '#e3beb8',
        'primary-container': '#8b0000',
        'on-surface-variant': '#5a403c',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#410000',
        'surface-variant': '#d3e4fe',
        'inverse-primary': '#ffb4a8',
        'secondary-fixed': '#e5e2e3',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#41474e',
        'tertiary-fixed': '#dde3eb',
        outline: '#8e706b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#3d4349',
        'on-primary-container': '#ff907f',
        background: '#f8f9ff',
        'on-tertiary-fixed': '#161c22',
        'surface-bright': '#f8f9ff',
        'inverse-on-surface': '#eaf1ff',
        'on-primary': '#ffffff',
        'on-secondary-container': '#636263',
        'secondary-container': '#e2dfe0',
        'surface-container-low': '#eff4ff',
        primary: '#610000',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        'headline-md': ['Atkinson Hyperlegible Next', 'sans-serif'],
        'headline-lg-mobile': ['Atkinson Hyperlegible Next', 'sans-serif'],
        'display-timer': ['Atkinson Hyperlegible Next', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'data-metric': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Atkinson Hyperlegible Next', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
